klever-io/kleverscan

src/components/Header/ConnectWallet/styles.ts
=> fix: connect wallet green ball

src/components/TransactionForms/CustomForms/CreateValidator.tsx, src/components/TransactionForms/CustomForms/Withdraw.tsx, src/types/contracts.ts
fixed createValidator ownerAddress missing field
=> fix(create-tx): review sdk params

src/components/Copy/index.tsx, src/pages/transaction/[hash].tsx, src/views/transactions/detail.ts
[Screencast from 2023-11-14 17-41-46.webm](https://github.com/klever-io/kleverscan/assets/63923113/0e4766fe-7c2a-4ae9-9da6-9d22832c7d28)
=> Kc 2128 fix tx signature hidden in tx page

src/pages/proposal/[number].tsx
=> fix(proposal): button expand

package.json, src/components/Table/ExportButton/index.tsx, src/components/Table/ExportButton/styles.ts, src/components/Table/index.tsx, src/utils/contracts/index.ts, src/utils/csv/index.ts, src/utils/precisionFunctions/index.ts, src/utils/receiptsFunctions/index.ts
* fix: export all csv rate limit
* chore: version 2.3.8
=> fix: export all csv rate limit (#123)

package.json, src/components/Detail/index.tsx, src/configs/navbar.ts, src/configs/transactions.ts, src/utils/contracts/index.ts
* fix: validators filter
* chore: feature flag for smart contract mainnet
* chore: version 2.4.3
=> Staging v2.4.3

package.json, src/components/Asset/AssetSummary/AssetITOSummary.tsx, src/components/Asset/AssetSummary/ParticipateModal/index.tsx, src/components/Asset/AssetSummary/ParticipateModal/styles.ts, src/components/Asset/AssetSummary/index.tsx, src/components/Asset/AssetSummary/styles.ts, src/components/Cards/CoinDataFetcher/CoinCard/index.tsx, src/components/Cards/CoinDataFetcher/CoinCard/styles.ts, src/components/ContextProviders/index.tsx, src/components/Contract/index.tsx, src/components/Copy/index.tsx, src/components/LaunchPad/Banner/styles.ts, src/components/LaunchPad/FAQCards/Card/styles.ts, src/components/LaunchPad/WalletBanner/index.tsx, src/components/NewTable/styles.ts, src/components/NewTable/widths.ts, src/components/Tour/index.tsx, src/components/TransactionForms/CustomForms/AssetTrigger.tsx, src/components/TransactionForms/FormInput/Select/styles.ts, src/components/TransactionForms/FormInput/styles.ts, src/components/TransactionForms/KDASelect/index.tsx, src/contexts/extension/index.tsx, src/contexts/participate/index.tsx, src/pages/ito/index.tsx, src/services/requests/ito/index.ts, src/types/contracts.ts, src/types/index.ts, src/utils/parseValues/index.ts, src/views/assets/index.ts, src/views/launchpad/index.ts
* fix: wallet image quality, faq cards link state color
* fix: ito pack precision parsing in launchpad page
* feat: particiapte NFT modal
* fix: launchpad link styles
* chore: improve nft participate modal user flow
* style: improve asset page loading skeleton
* chore: create participate modal context, apply to ito page
* style: better fungible token participate modal
* fix: fungible participate modal correct calculation
* fix: return button logic
* feat: tx hash on ito page
* style: ito page table
* fix: tour modal
* fix: create tx z-index refactor
* 2.5.12
* style: scale down copy icon
* fix: clear participate modal data, adjust font, add ticker
=> Chore/2 5 12 (#161)

package.json, src/components/LaunchPad/Banner/styles.ts
* style: launchpad banner lateral fading
* 2.5.13
=> Chore/2 5 13 (#163)

src/components/Asset/AssetSummary/index.tsx, src/components/Cards/CoinDataFetcher/CoinCard/index.tsx, src/components/Footer/index.tsx, src/components/Header/WalletHelp/index.tsx, src/components/LaunchPad/FAQCards/Card/index.tsx, src/components/LaunchPad/WalletBanner/index.tsx, src/components/Map/index.tsx, src/pages/404.tsx, src/pages/create-transaction/index.tsx, src/pages/ito/index.tsx
- Fix: anchor's `rel` attribute for external redirect links;
- Fix: Lint issues on the files that I've worked on - `useState` destructuring, fragments, etc.
=> fix: remaining external links adjustments

src/configs/footer.ts, src/test/mocks/asset-mocks.ts
- Fix: Blockchain whitepaper link ref - moved from squarespace to google storage.
=> fix: blockchain whitepaper link ref

src/components/Asset/ITOTab.tsx, src/components/Asset/KDAPoolTab.tsx, src/components/Asset/MoreTab.tsx, src/components/Asset/OverviewTab.tsx, src/components/Asset/StakingHistoryTab.tsx, src/components/Asset/StakingRoyaltiesTab.tsx, src/components/Asset/URIsTab.tsx, src/pages/asset/[asset].tsx, src/styles/common/index.ts, src/views/assets/detail.ts, src/views/assets/index.ts, src/views/transactions/detail.ts
- Chore: Asset tabs components and layout improvements - Overview, Staking History, and Staking Royalties tab;
- Fix: Lint issues.
=> chore: asset tabs components and layout improvements

src/components/Asset/StakingRoyaltiesTab.tsx, src/components/Tabs/Buckets/index.tsx, src/services/requests/account/index.ts
- Fix: Account assets buckets data parsing and other adjustments;
- Fix: Assets' staking royalties transfer percentage value.
=> fix: account assets buckets data parsing and other adjustments

src/components/Contract/styles.ts, src/components/Home/CoinDataFetcher/CoinCard/styles.ts, src/components/Home/HomeTransactions/ChartDailyTransactions/index.tsx, src/views/home.ts
- Refactor: Transactions chart improvements - total transactions/transactions in a specific period, change indicators, filters, and dx.
=> refactor: txs chart and related components improvements and fixes

src/services/requests/account/index.ts
- Fix: Account assets buckets data parsing adjustments;
- Fix: Lint issues.
=> fix: account assets buckets data parsing adjustments

src/components/Cards/CardDataFetcher/HomeDataCards/index.tsx, src/components/HomeTransactions/ChartDailyTransactions/index.tsx
- Fix: Total transactions by period sum calc instead of difference of values.
=> fix: total transactions by period sum instead of diff

package.json, src/components/Tabs/Buckets/index.tsx, src/services/requests/account/index.ts, src/types/index.ts
* fix: buckets tab row section
* 2.7.5
* fix: account request conditional
=> Staging v2.7.5

src/components/Asset/AssetSummary/ParticipateModal/index.tsx, src/components/Asset/AssetSummary/ParticipateModal/styles.ts, src/components/Home/CardDataFetcher/HomeDataCards/index.tsx, src/types/home.ts
- Chore: Validate token precision on ITO feature;
- Chore: TPS card adjustments.
=> DW-1556 - Validate token precision on ITO feature and TPS card adjustments

package.json, src/components/Home/BlockCardFetcher/index.tsx, src/components/Home/QuickAccess/styles.ts
* style: quick actions hover table viewl all
* 2.7.7
=> Style/quick actions hover table view all (#211) [v2.7.7]

package.json, src/pages/account/[account].tsx, src/pages/accounts/index.tsx, src/pages/asset/[asset].tsx, src/pages/assets/index.tsx, src/pages/charts/index.tsx, src/pages/encoding-converter/index.tsx, src/pages/index.tsx, src/pages/ito/index.tsx, src/pages/marketplace/[marketplace].tsx, src/pages/marketplaces/index.tsx, src/pages/proposal/[number].tsx, src/pages/proposals/index.tsx, src/pages/validator/[hash].tsx, src/pages/verify-signature/index.tsx
* fix: static translations
* 2.7.10
=> fix: static translations (#221)

src/pages/api/proxy.ts, src/services/api.ts, src/services/requests/account/index.ts, src/services/requests/home/index.ts
Reverts klever-io/kleverscan#252
=> Revert "chore: remove api proxy"

src/components/TransactionContractComponents/index.tsx, src/components/TransactionForms/CustomForms/utils/index.ts, src/types/contracts.ts, src/views/accounts/detail.ts
…… (#414)
* fix: enhance royalties display and structure in TransactionContract component
* fix: add split royalties handling and improve royalty parsing logic
=> Bump Staging - 14 - May - 2025 14:31H
